name: build docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: login to ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          tags: 352489376382.dkr.ecr.eu-central-1.amazonaws.com/web-app:${{ github.sha }}
          push: true
      - name: commit tag on prod
        run: 'sed -i "s/tag: .*/tag: ${{ github.sha }}/g" .helm/values-prod.yaml'
      - uses: EndBug/add-and-commit@v5.2.0
        with:
          author_name: Loop Service Account
          author_email: service-account@loop.markets
          message: '[ci skip] Bump prod environment to ${{ github.sha }}'
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: clear cloudflare cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_PROD }}/purge_cache" \
          -H "X-Auth-Email: aws@loop.markets" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
